"""initial inference and evidence schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd8552cb5cda7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('identifier', sa.String(length=80), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('prompt_versions',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('sessions',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_cursor', 'sessions', ['created_at', 'id'], unique=False)
    op.create_table('audio_assets',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_session_id'), 'audio_assets', ['session_id'], unique=False)
    op.create_table('utterances',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence > 0'),
    sa.CheckConstraint('superseded_by IS NULL OR superseded_by > sequence'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence')
    )
    op.create_table('inference_jobs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audio_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('replay_of', sa.UUID(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('QUEUED','INGESTING','TRANSCRIBING','REDACTING','GENERATING','VALIDATING','REVIEW_REQUIRED','COMPLETED','FAILED')"),
    sa.CheckConstraint('attempts >= 0'),
    sa.CheckConstraint('progress BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['model_version'], ['model_versions.version'], ),
    sa.ForeignKeyConstraint(['prompt_version'], ['prompt_versions.version'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_jobs_session_id'), 'inference_jobs', ['session_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inference_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_unpublished', 'inference_events', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_index(op.f('ix_inference_events_job_id'), 'inference_events', ['job_id'], unique=False)
    op.create_table('inference_runs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('redacted_input_hash', sa.String(length=64), nullable=False),
    sa.Column('redacted_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ),
    sa.ForeignKeyConstraint(['model_version'], ['model_versions.version'], ),
    sa.ForeignKeyConstraint(['prompt_version'], ['prompt_versions.version'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_runs_session_cursor', 'inference_runs', ['session_id', 'created_at', 'id'], unique=False)
    op.create_table('job_outbox',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('generated_notes',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('REVIEW_REQUIRED','APPROVED','REJECTED')"),
    sa.ForeignKeyConstraint(['run_id'], ['inference_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_notes_review_cursor', 'generated_notes', ['created_at', 'id'], unique=False, postgresql_where=sa.text("status = 'REVIEW_REQUIRED'"))
    op.create_table('generated_sections',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['generated_notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'kind', 'position')
    )
    op.create_index(op.f('ix_generated_sections_note_id'), 'generated_sections', ['note_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['generated_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_note_id'), 'review_actions', ['note_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['generated_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_links_section_id'), 'evidence_links', ['section_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['generated_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_evidence_links_section_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_review_actions_note_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_generated_sections_note_id'), table_name='generated_sections')
    op.drop_table('generated_sections')
    op.drop_index('ix_notes_review_cursor', table_name='generated_notes', postgresql_where=sa.text("status = 'REVIEW_REQUIRED'"))
    op.drop_table('generated_notes')
    op.drop_table('job_outbox')
    op.drop_index('ix_runs_session_cursor', table_name='inference_runs')
    op.drop_table('inference_runs')
    op.drop_index(op.f('ix_inference_events_job_id'), table_name='inference_events')
    op.drop_index('ix_events_unpublished', table_name='inference_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('inference_events')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_inference_jobs_session_id'), table_name='inference_jobs')
    op.drop_table('inference_jobs')
    op.drop_table('utterances')
    op.drop_index(op.f('ix_audio_assets_session_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index('ix_sessions_cursor', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('prompt_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
